------------------------------------------------------------------------------
--  Iour.Fibers.Race_Witness -- makes SPARK check a fiber body for data
--  races.  Without one it is checked for nothing at all.
--
--  Nothing instantiates this by hand.  Iour.Fibers.Job instantiates it for
--  every job the program registers, so registering a fiber body is what
--  puts it under the data-race rule; there is no list to keep and nothing
--  for a consumer to forget.  What follows is why it has to exist and why
--  it has the shape it has.
--
--  SPARK's data-race rule fires when an unsynchronized object is reachable
--  from two tasks.  A fiber is entered through the context switch's
--  assembly trampoline, so gnatprove analyses Iour.Fibers.Fiber_Main as a
--  subprogram nobody calls: no fiber body is in any task's call graph, and
--  the rule never gets the chance to look.  State a program shares between
--  its fibers was therefore unchecked by default, silently.
--
--  This states the truth the trampoline hides -- this body runs on shards,
--  and there is more than one shard -- by putting it in two tasks' call
--  graphs.
--
--  **Nothing here is ever executed, for two independent reasons, and the
--  order of the statements in each task body is what buys the first.**
--  Each task's first act is to call Never_Opens.Park, an entry whose
--  barrier is False and which nothing ever opens; the call does not
--  return, so the call to Work below it is never reached.  And were it
--  reached, Run is False and nothing anywhere assigns it.  gnatprove folds
--  neither -- it cannot fold an entry call, and Async_Writers says an
--  outside agent might write Run -- so Work stays in the call graph either
--  way, which is the whole point of the task.
--
--  Measured, not reasoned about: an Exit_Process at the top of Never_Runs,
--  in a scratch build, fires on every run of `smoke` when the call comes
--  before the wait, and on none when it comes after.
--
--  It would be better still if these were ghost code and did not exist at
--  run time.  They cannot be.  GNAT rejects the aspect twice over --
--  `aspect "Ghost" cannot apply to a task type` and `ghost object ...
--  cannot be synchronized` -- and behind that is a rule no arrangement
--  gets around: ghost code may not write non-ghost state, and reaching a
--  fiber body that writes real state is the entire purpose.  Dropping the
--  objects for a bare task type does not work either: a task type with no
--  objects is silent, and so is one with a single object.  Two real task
--  objects per job is the floor.
--
--  **Two tasks, not one, and they are both here.**  The rule needs two
--  callers of the same body.  One task per job would catch state shared
--  between *different* jobs and miss state one job shares with itself
--  across shards -- which is the commoner case and the one that found
--  Echo_Server_App.Next_Core.  The previous arrangement got its second
--  caller from the environment task, by having the main subprogram call
--  into a per-program witness listing every fiber body; that cost one
--  thread instead of two but put the list, and the chance to forget an
--  entry, in the consumer.  The list is gone and the second thread is what
--  it cost.
--
--  Why this cannot live in Iour.Fibers.Job itself, which is where it
--  belongs: that package's private part is SPARK_Mode => Off for the one
--  'Access the runtime contains, an Off private part forces an Off body,
--  and a task body in an Off package body is analysed for nothing.  The
--  witness needs a body gnatprove will look at, so it is a separate
--  generic with a body of its own, instantiated from Job's *visible*
--  part, which is On.
--
--  Four things about the shape, each established by experiment.  Do not
--  re-derive them; three are the opposite of the obvious guess.
--
--    * The guard must be one gnatprove cannot fold.  A statically False
--      one is pruned -- "this statement is never reached" -- and the race
--      check stays silent.  Run is Atomic and nothing sets it, so the call
--      stays in the call graph and out of the program.
--
--    * The elaboration of the instance cannot be the second caller.
--      Making it one would have got this to a single task per job, and
--      SPARK rejects it outright: "cannot write ... during elaboration of
--      ... [E0008]".  The guard does not help, because that is a flow
--      rule over the call graph rather than anything gnatprove folds.
--
--    * The witness must be in the partition's closure.  Put in a unit
--      nothing withs -- a separate source directory selected by a scenario
--      variable, say -- it is not analysed and reports nothing, even under
--      -U.  That is why this is compiled into the program rather than
--      being a proof-only artefact, and it has the happy consequence that
--      the proved program and the shipped program are the same program.
--
--    * It has to run at Runtime_Priority.  At any other priority every
--      protected object it reaches reports a possible ceiling violation
--      instead of the thing you are looking for.
--
--  The cost is two threads per *kind* of fiber -- not per fiber -- each of
--  which starts, blocks on its first statement, and never runs again.
--  Blocks, rather than spinning: Jorvik forbids a task body from running
--  off its end, so they wait on a barrier that never opens, exactly as
--  Iour.Shards does for shards past Shard_Count.
--
--  What this does not model is the scheduling.  SPARK cannot tell two
--  fibers on one shard, which cannot preempt each other, from two on
--  different shards, which race -- so it treats both as racing.  That is
--  conservative, which is the right way for a check to be wrong, and it is
--  why Echo_Server_App's Next_Core had to become Atomic rather than be
--  justified by the shard-confinement argument it used to carry.
------------------------------------------------------------------------------

generic
   --  The fiber body to witness: the same actual its Iour.Fibers.Job
   --  instance was given.
   with procedure Work (Arg : Fiber_Argument);

package Iour.Fibers.Race_Witness with SPARK_Mode => On is

   pragma Elaborate_Body;

end Iour.Fibers.Race_Witness;
